### ISSUE TITLE
How to use " cwltool pipeline.cwl" with in-house human PBMC CITE-Seq data ?

### ISSUE THREAD

**Issue by qicheng-ma** [hubmapconsortium/azimuth-annotate#1]
Dear Austin,

I have both cwltool and azimuth-annotate installed:
> cwltool pipeline.cwl
INFO /mnt/efs/home/stb3865/software/anaconda3/bin/cwltool 3.1.20211107152837
INFO Resolved 'pipeline.cwl' to 'file:///mnt/efs/home/stb3865/software/azimuth-annotate/pipeline.cwl'
usage: pipeline.cwl [-h] --matrix MATRIX --reference REFERENCE --secondary-analysis-matrix SECONDARY_ANALYSIS_MATRIX
                    [job_order]
pipeline.cwl: error: the following arguments are required: --matrix, --reference, --secondary-analysis-matrix

I have the  in-house human PBMC CITE-Seq data,  here are my questions:

1) For human PBMC (https://seurat.nygenome.org/azimuth/references/v1.0.0/human_pbmc), what would the two-level code be ?
2) Am I right if I supply scRNA matrix for --matrix  and ADT matrix for --secondary-analysis-matrix ?

Thanks in advance!

**Comment by AustinHartman** [comment]
Hi,
azimuth-annotate is used to annotate datasets which come from a specific HuBMAP pipeline and so if you have processed your data in some other way azimuth-annotate will not work. I would recommend you try uploading your dataset to the azimuth web app here: [https://app.azimuth.hubmapconsortium.org/app/human-pbmc](https://app.azimuth.hubmapconsortium.org/app/human-pbmc). If you are curious what code the azimuth web app used to process your data, you can download that after running under "Download Results" -> "Analysis script template"
